name: Deploy Professional Profile based on angular

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    name: Deploy via angular-cli-ghpages
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Install Angular CLI gh-pages
      run: npm i angular-cli-ghpages --save-dev

    - name: Build Angular project
      run: ng build --prod --base-href "https://araujoit.github.io/professional-profile/"

    - name: npx angular-cli-ghpages --dir=dist/professional-profile