name: Deploy Professional Profile based on angular

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    name: Deploy via angular-cli-ghpages
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    # - name: Run tests
    #   run: npm run test

    - name: Build
      run: npm run build

    - name: Install Angular Cli Github Pages
      run: npm i -g angular-cli-ghpages

    - name: Deploy to gh pages
      if: success()
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: npm run deploy
