name: Deploy Professional Profile based on angular

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    name: Deploy via angular-cli-ghpages
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Angular project
      run: npm run build
      
    - name: Deploy to GitHub Pages
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
        repository_nwo: ${{ github.repository }}
        branch: gh-pages
        folder: dist
      run: npm