name: Deploy Professional Profile based on angular

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    name: Deploy via angular-cli-ghpages
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    # - name: Run tests
    #   run: npm run test

    - name: Build
      run: npm run build

    # - name: Deploy on Github Pages
    #   run: ng deploy --repo=git@github.com:araujoit/professional-profile.git --name=araujoit